config/routes.rb
Rails.application.routes.draw do
  resources :questions

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
	belongs_to :user
	has_many :comments, :as => :commentable
	has_many :votes, :as => :votable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :commentable, :polymorphic => true
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	has_many :answers
	has_many :comments, :as => :commentable
	has_many :votes, :as => :votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes

end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :votable, :polymorphic => true
	belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def destroy
  end

  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except:[:show]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def destroy
  end

  def new
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @current_user = current_user
  end

  def show
  end

  def edit
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  def new
    @question = Question.new
  end

  def create
    @question =  Question.new(question_params)
    if @question.save
      redirect_to questions_path
    else
      render 'new'
    end
  end

  private
    def question_params
      params.require(:question).permit(:title, :content).merge(user_id: current_user.id)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def destroy
  end

  def new
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/answers/destroy.html.erb
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>

app/views/answers/edit.html.erb
<h1>Answers#edit</h1>
<p>Find me in app/views/answers/edit.html.erb</p>

app/views/answers/index.html.erb
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>

app/views/answers/new.html.erb
<h1>Answers#new</h1>
<p>Find me in app/views/answers/new.html.erb</p>

app/views/answers/show.html.erb
<h1>Answers#show</h1>
<p>Find me in app/views/answers/show.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowStackOver</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/questions/index.html.erb
<h1>Questions#index</h1>

<% u = @current_user %>

<h3>Preguntas de Jakintero</h3>
<p>Question title:<%= u.questions.last.title %></p>
<p>Question content:<%= u.questions.last.content %></p>

<% @questions.each do |question| %>
		<p> Título:<%= question.title %></p>
		<p> Contenido:<%= question.content %></p>
		<% if current_user.id == question.user.id %>
			<%= link_to 'Borrar', question_path(question),
														method: :delete,
														data: { confirm: 'Are you sure?' } %>
		<% end %>
<% end %>


<ul>
	<td><h3> Preguntas de todos los usuarios:<h3><br></td>
			<td><% @questions.each do |question| %></td>
					<td><p> Título:<%= question.title %></p></td>
					<td><h4> Contenido:<%= question.content %></h4>
			<% end %>
</ul>

<% if user_signed_in? %>
  <a rel="nofollow" data-method="delete" href="/users/sign_out">
  Salir <span class="sr-only"></span></a>
<% end %>
<br>
<%= link_to "Create", new_question_path %>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>




<h1>Nueva Pregunta</h1>

<%= form_for @question do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/votes/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>

app/views/votes/edit.html.erb
<h1>Votes#edit</h1>
<p>Find me in app/views/votes/edit.html.erb</p>

app/views/votes/index.html.erb
<h1>Votes#index</h1>
<p>Find me in app/views/votes/index.html.erb</p>

app/views/votes/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>

app/views/votes/show.html.erb
<h1>Votes#show</h1>
<p>Find me in app/views/votes/show.html.erb</p>